workflows:
  android-workflow:
    name: Android Build
    max_build_duration: 60
    instance_type: mac_mini_m2
    environment:
      vars:
        PACKAGE_NAME: "com.ansar.ansar_team"
        GRADLE_VERSION: "7.5"
    scripts:
      - name: Setup Flutter
        script: |
          flutter --version
          flutter upgrade
          flutter pub cache repair
      - name: Verify project structure
        script: |
          pwd
          ls -la
          flutter doctor -v
      - name: Navigate to project directory
        script: |
          cd ansar_team
          pwd
          ls -la
          if [ -f "pubspec.yaml" ]; then
            echo "Found pubspec.yaml in project directory"
          else
            echo "pubspec.yaml not found in project directory"
            find . -name "pubspec.yaml"
          fi
      - name: Get Flutter packages
        script: |
          cd ansar_team
          flutter pub get
      - name: Flutter analyze
        script: |
          cd ansar_team
          flutter analyze
      - name: Flutter test
        script: |
          cd ansar_team
          flutter test
      - name: Build APK
        script: |
          cd ansar_team
          flutter build apk --release
      - name: Build App Bundle
        script: |
          cd ansar_team
          flutter build appbundle --release
    artifacts:
      - ansar_team/build/app/outputs/flutter-apk/app-release.apk
      - ansar_team/build/app/outputs/bundle/release/app-release.aab
    publishing:
      email:
        recipients:
          - aallaannssaarr@gmail.com

