workflows:
  android-workflow:
    name: Android Build
    max_build_duration: 60
    instance_type: mac_mini_m2
    environment:
      vars:
        PACKAGE_NAME: "com.ansar.ansar_team"
    scripts:
      - name: Get Flutter packages
        script: |
          flutter pub get
      
      - name: Check Flutter version
        script: |
          flutter --version
      
      - name: Run Flutter doctor
        script: |
          flutter doctor -v
      
      - name: Run Flutter analyze with detailed output
        script: |
          flutter analyze --verbose
      
      - name: Build Release APK
        script: |
          flutter build apk --release --verbose
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
    publishing:
      email:
        recipients:
          - ansar.team.app@gmail.com

  ios-workflow:
    name: iOS Build
    max_build_duration: 60
    instance_type: mac_mini_m2
    environment:
      groups:
        - apple_credentials
      vars:
        XCODE_WORKSPACE: "ios/Runner.xcworkspace"
        XCODE_SCHEME: "Runner"
    scripts:
      - name: Get Flutter packages
        script: |
          flutter pub get
      - name: Flutter analyze
        script: |
          flutter analyze
      - name: Build iOS
        script: |
          flutter build ios --release --no-codesign
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      email:
        recipients:
          - your-email@example.com

env_groups:
  google_credentials:
    vars:
      GOOGLE_PLAY_CREDENTIALS: encrypted_google_play_credentials
  apple_credentials:
    vars:
      APP_STORE_CONNECT_ISSUER_ID: encrypted_app_store_connect_issuer_id
      APP_STORE_CONNECT_KEY_IDENTIFIER: encrypted_app_store_connect_key_identifier
      APP_STORE_CONNECT_PRIVATE_KEY: encrypted_app_store_connect_private_key
      CERTIFICATE_PRIVATE_KEY: encrypted_certificate_private_key
      CERTIFICATE_PASSWORD: encrypted_certificate_password
      DISTRIBUTION_CERTIFICATE: encrypted_distribution_certificate
      DISTRIBUTION_CERTIFICATE_PASSWORD: encrypted_distribution_certificate_password
      PROVISIONING_PROFILE: encrypted_provisioning_profile 