workflows:
  android-workflow:
    name: Android Build
    max_build_duration: 60
    instance_type: mac_mini_m2
    environment:
      vars:
        PACKAGE_NAME: "com.ansar.ansar_team"
    scripts:
      - name: Setup and Environment Check
        script: |
          echo "=== Environment Setup ==="
          echo "Current directory:"
          pwd
          echo "Moving to Flutter project directory..."
          cd flutter_app
          echo "New directory:"
          pwd
          echo "Directory contents:"
          ls -la
          
          echo "=== Flutter Environment ==="
          flutter --version
          flutter doctor -v
          
          echo "=== Dependencies Check ==="
          flutter pub outdated
      
      - name: Update Dependencies
        script: |
          echo "=== Updating Flutter ==="
          flutter upgrade
          
          echo "=== Updating Dependencies ==="
          flutter pub upgrade
          flutter pub get
      
      - name: Code Analysis and Testing
        script: |
          echo "=== Running Code Analysis ==="
          flutter analyze --verbose > analysis_report.txt
          
          echo "=== Running Tests ==="
          flutter test --verbose > test_report.txt
          
          echo "=== Generating Reports ==="
          echo "Analysis Report:"
          cat analysis_report.txt
          echo "Test Report:"
          cat test_report.txt
      
      - name: Build APK
        script: |
          echo "=== Building Release APK ==="
          flutter build apk --release --verbose > build_report.txt
          
          echo "=== Build Report ==="
          cat build_report.txt
    artifacts:
      - flutter_app/build/app/outputs/flutter-apk/app-release.apk
      - flutter_app/analysis_report.txt
      - flutter_app/test_report.txt
      - flutter_app/build_report.txt
    publishing:
      email:
        recipients:
          - ansar.team.app@gmail.com

  ios-workflow:
    name: iOS Build
    max_build_duration: 60
    instance_type: mac_mini_m2
    environment:
      groups:
        - apple_credentials
      vars:
        XCODE_WORKSPACE: "ios/Runner.xcworkspace"
        XCODE_SCHEME: "Runner"
    scripts:
      - name: Get Flutter packages
        script: |
          flutter pub get
      - name: Flutter analyze
        script: |
          flutter analyze
      - name: Build iOS
        script: |
          flutter build ios --release --no-codesign
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      email:
        recipients:
          - your-email@example.com

env_groups:
  google_credentials:
    vars:
      GOOGLE_PLAY_CREDENTIALS: encrypted_google_play_credentials
  apple_credentials:
    vars:
      APP_STORE_CONNECT_ISSUER_ID: encrypted_app_store_connect_issuer_id
      APP_STORE_CONNECT_KEY_IDENTIFIER: encrypted_app_store_connect_key_identifier
      APP_STORE_CONNECT_PRIVATE_KEY: encrypted_app_store_connect_private_key
      CERTIFICATE_PRIVATE_KEY: encrypted_certificate_private_key
      CERTIFICATE_PASSWORD: encrypted_certificate_password
      DISTRIBUTION_CERTIFICATE: encrypted_distribution_certificate
      DISTRIBUTION_CERTIFICATE_PASSWORD: encrypted_distribution_certificate_password
      PROVISIONING_PROFILE: encrypted_provisioning_profile 