workflows:
  android-build:
    name: Android Release Build
    max_build_duration: 60
    instance_type: mac_mini_m2
    environment:
      groups:
        - android_signing  # لمفاتيح توقيع Android فقط
      flutter: "stable"  # أو إصدار محدد مثل "3.19.5"
      vars:
        PACKAGE_NAME: "com.ansar.ansar_team"

    scripts:
      # ----------------------
      # إعدادات مسبقة
      # ----------------------
      - name: Project Setup
        script: |
          echo "=== 🔍 التحقق من هيكل المشروع ==="
          
          if [ ! -f "flutter_app/pubspec.yaml" ]; then
            echo "❌ ملف pubspec.yaml غير موجود!"
            exit 1
          fi
          
          cd flutter_app
          echo "✔️ تم التحقق من هيكل المشروع"

      # ----------------------
      # إدارة التبعيات
      # ----------------------
      - name: Dependencies
        script: |
          echo "=== 📦 تثبيت التبعيات ==="
          cd flutter_app
          
          flutter clean
          rm -rf android/.gradle  # تنظيف ذاكرة التخزين المؤقت
          flutter pub cache repair
          flutter pub get

      # ----------------------
      # مراقبة الجودة
      # ----------------------
      - name: Code Quality
        script: |
          echo "=== 🔬 فحص الجودة ==="
          cd flutter_app
          
          flutter analyze --no-pub > analysis_report.txt
          flutter test --coverage > test_report.txt

      # ----------------------
      # بناء APK
      # ----------------------
      - name: Build APK
        script: |
          echo "=== 🛠️ بناء الإصدار النهائي ==="
          cd flutter_app
          
          # إنشاء ملف local.properties تلقائيًا
          echo "flutter.sdk=${FLUTTER_ROOT}" > android/local.properties
          echo "sdk.dir=${ANDROID_SDK_ROOT}" >> android/local.properties
          
          flutter build apk --release \
            --dart-define=APP_ENV=prod \
            --verbose \
            > build_report.txt

    # ----------------------
    # المخرجات
    # ----------------------
    artifacts:
      - flutter_app/build/app/outputs/flutter-apk/app-release.apk
      - flutter_app/analysis_report.txt
      - flutter_app/test_report.txt
      - flutter_app/build_report.txt

    # ----------------------
    # الإشعارات
    # ----------------------
    publishing:
      email:
        recipients:
          - aallaannssaarr@gmail.com
