workflows:
  android-workflow:
    name: Android Build
    max_build_duration: 60
    instance_type: mac_mini_m2
    environment:
      vars:
        PACKAGE_NAME: "com.ansar.ansar_team"
        GRADLE_VERSION: "7.5"
    scripts:
      - name: Setup Flutter
        script: |
          flutter --version
          flutter upgrade
          flutter pub cache repair
      - name: Verify project structure
        script: |
          pwd
          ls -la
          cd .
          flutter doctor -v
      - name: Get Flutter packages
        script: flutter pub get
      - name: Flutter analyze
        script: flutter analyze
      - name: Flutter test
        script: flutter test
      - name: Build APK
        script: flutter build apk --release
      - name: Build App Bundle
        script: flutter build appbundle --release
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
      - build/app/outputs/bundle/release/app-release.aab
    publishing:
      email:
        recipients:
          - aallaannssaarr@gmail.com

