
workflows:
  build-android:
    name: Build Android APK
    max_build_duration: 15
    environment:
      flutter: stable
      xcode: latest
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: 'main'
          include: true
    scripts:
      - name: Get dependencies
        script: |
          cd product_inquiry_app
          flutter pub get
      - name: Build release APK
        script: |
          cd product_inquiry_app
          flutter build apk --release
    artifacts:
      - product_inquiry_app/build/app/outputs/flutter-apk/app-release.apk
