workflows:
  build-android:
    name: Build Android APK
    max_build_duration: 15
    environment:
      flutter: stable
    scripts:
      - name: Move into app directory
        script: |
          cd product_inquiry_app
          flutter pub get
          flutter build apk --release
    artifacts:
      - product_inquiry_app/build/app/outputs/flutter-apk/app-release.apk
