workflows:
  android-workflow:
    name: Android Build
    max_build_duration: 60
    instance_type: mac_mini_m2
    integrations:
      firebase:
        distribution_groups: testers
    environment:
      flutter: stable
      xcode: latest
      node: latest
      groups:
        - google_credentials
        - firebase_credentials
      vars:
        PACKAGE_NAME: "com.ansarteam.app"
    scripts:
      - name: Setup Flutter
        script: |
          flutter --version
          flutter upgrade
          flutter pub cache repair
          flutter doctor -v
      - name: Verify project structure
        script: |
          pwd
          ls -la
          echo "Current directory contents:"
          find . -type f -name "pubspec.yaml"
      - name: Navigate to project directory
        script: |
          cd final_fixes
          pwd
          ls -la
          if [ -f "pubspec.yaml" ]; then
            echo "Found pubspec.yaml in project directory"
            cat pubspec.yaml | grep "name:"
          else
            echo "pubspec.yaml not found in project directory"
            find . -name "pubspec.yaml"
          fi
      - name: Get Flutter packages
        script: |
          cd final_fixes
          flutter pub get
      - name: Flutter analyze
        script: |
          cd final_fixes
          flutter analyze
      - name: Flutter test
        script: |
          cd final_fixes
          flutter test
      - name: Build APK
        script: |
          cd final_fixes
          flutter build apk --release --verbose
      - name: Build App Bundle
        script: |
          cd final_fixes
          flutter build appbundle --release --verbose
    artifacts:
      - final_fixes/build/app/outputs/flutter-apk/app-release.apk
      - final_fixes/build/app/outputs/bundle/release/app-release.aab
    publishing:
      email:
        recipients:
          - your-email@example.com

  ios-workflow:
    name: iOS Build
    max_build_duration: 60
    instance_type: mac_mini_m2
    integrations:
      firebase:
        distribution_groups: testers
    environment:
      flutter: stable
      xcode: latest
      node: latest
      groups:
        - google_credentials
        - firebase_credentials
        - ios_certificates
      vars:
        BUNDLE_ID: "com.ansarteam.app"
    scripts:
      - name: Get Flutter packages
        script: flutter pub get
      - name: Flutter analyze
        script: flutter analyze
      - name: Build IPA
        script: flutter build ipa --release
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      email:
        recipients:
          - your-email@example.com

