name: ansar_team
description: تطبيق فريق أنصار

version: 1.0.0+1

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  # تحديث المكونات الإضافية إلى أحدث إصدار
  flutter_plugin_android_lifecycle: ^2.0.27
  file_picker: ^10.1.2
  permission_handler: ^12.0.0+1
  flutter_webrtc: ^0.13.1+hotfix.1
  local_auth: ^2.1.8  # استخدم الحزمة الرئيسية بدلاً من local_auth_android
  image_picker: ^1.0.7  # استخدم الحزمة الرئيسية بدلاً من image_picker_android
  
  # باقي المكتبات المستخدمة في المشروع
  flutter_sound: ^9.2.13
  path_provider: ^2.1.2
  url_launcher: ^6.2.5
  flutter_secure_storage: ^9.2.4
  
  # باقي التبعيات الموجودة في المشروع
  cupertino_icons: ^1.0.6
  firebase_core: ^2.32.0
  firebase_auth: ^4.20.0
  firebase_storage: ^11.7.7
  cloud_firestore: ^4.17.5
  firebase_messaging: ^14.9.4
  firebase_database: ^10.5.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  build_runner: ^2.4.14

flutter:
  uses-material-design: true
  
  assets:
    - assets/sounds/
    - assets/images/
    - assets/icons/
    - assets/animations/
  
  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-Medium.ttf
          weight: 500
        - asset: assets/fonts/Cairo-Regular.ttf
          weight: 400
        - asset: assets/fonts/Cairo-Bold.ttf
          weight: 700
