name: ansar_team
description: تطبيق فريق الأنصار لإدارة شؤون العمل
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Firebase
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.2
  cloud_firestore: ^5.6.6
  firebase_storage: ^12.4.5
  firebase_messaging: ^15.2.5
  firebase_database: ^11.3.5

  # المصادقة
  local_auth: ^1.0.49
  shared_preferences: ^2.5.0
  flutter_secure_storage: ^9.2.4

  # واجهة المستخدم
  cupertino_icons: ^1.0.5
  flutter_svg: ^2.0.7
  cached_network_image: ^3.4.1
  shimmer: ^3.0.0
  lottie: ^3.3.1
  flutter_spinkit: ^5.2.0

  # إدارة الحالة
  provider: ^6.0.5

  # المكالمات الصوتية
  flutter_webrtc: ^0.13.1
  sdp_transform: ^0.3.2
  permission_handler: ^12.0.0+1

  # أدوات
  intl: ^0.20.2
  path_provider: ^2.1.0
  uuid: ^3.0.7
  http: ^1.3.0
  url_launcher: ^6.1.12
  share_plus: ^10.1.4
  image_picker: ^1.0.7
  file_picker: ^10.1.0
  just_audio: ^0.9.46
  image: ^4.5.4
  flutter_plugin_android_lifecycle: ^2.0.27

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2
  mockito: ^5.4.2
  build_runner: ^2.4.6

flutter:
  uses-material-design: true

  assets:
    - assets/logo.jpg
    - assets/sounds/
    - assets/images/
    - assets/icons/
    - assets/animations/

  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-Regular.ttf
        - asset: assets/fonts/Cairo-Bold.ttf
          weight: 700
        - asset: assets/fonts/Cairo-Medium.ttf
          weight: 500
        - asset: assets/fonts/Cairo-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Cairo-Light.ttf
          weight: 300

